package net.minecraft.src;

public class GenLayerDimensionWater extends GenLayer
{
    private GenLayer field_35512_b;
    private GenLayer field_35513_c;
    private WorldProviderBase worldProvider;

    public GenLayerDimensionWater(long l, GenLayer genlayer, GenLayer genlayer1, WorldProviderBase worldproviderbase)
    {
        super(l);
        field_35512_b = genlayer;
        field_35513_c = genlayer1;
        worldProvider = worldproviderbase;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the world's global seed (passed in as an
     * argument).
     */
    public void initWorldGenSeed(long l)
    {
        field_35512_b.initWorldGenSeed(l);
        field_35513_c.initWorldGenSeed(l);
        super.initWorldGenSeed(l);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int i, int j, int k, int l)
    {
        int ai[] = field_35512_b.getInts(i, j, k, l);
        int ai1[] = field_35513_c.getInts(i, j, k, l);
        int ai2[] = IntCache.getIntCache(k * l);

        for (int i1 = 0; i1 < k * l; i1++)
        {
            BiomeGenBase biomegenbase = worldProvider.setOceanBiomes(null, this);

            if (biomegenbase != null && ai[i1] == biomegenbase.biomeID)
            {
                ai2[i1] = ai[i1];
                continue;
            }

            if (ai1[i1] >= 0)
            {
                BiomeGenBase biomegenbase1 = worldProvider.setRiverBiomes(BiomeGenBase.biomeList[ai[i1]], this);

                if (biomegenbase1 != null)
                {
                    ai2[i1] = biomegenbase1.biomeID;
                }
                else
                {
                    ai2[i1] = ai1[i1];
                }
            }
            else
            {
                ai2[i1] = ai[i1];
            }
        }

        return ai2;
    }
}
