package net.minecraft.src;

public class GenLayerDimensionMajorBiome extends GenLayer
{
    private WorldProviderBase worldProvider;
    private BiomeGenBase allowedBiomes[];

    public GenLayerDimensionMajorBiome(long l, GenLayer genlayer, WorldProviderBase worldproviderbase)
    {
        super(l);
        parent = genlayer;
        worldProvider = worldproviderbase;
        allowedBiomes = worldproviderbase.setMajorBiomes();
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int i, int j, int k, int l)
    {
        int ai[] = parent.getInts(i, j, k, l);
        int ai1[] = IntCache.getIntCache(k * l);

        for (int i1 = 0; i1 < l; i1++)
        {
            for (int j1 = 0; j1 < k; j1++)
            {
                initChunkSeed(j1 + i, i1 + j);
                int k1 = ai[j1 + i1 * k];
                BiomeGenBase biomegenbase = worldProvider.setOceanBiomes(null, this);

                if (biomegenbase != null && k1 == biomegenbase.biomeID)
                {
                    ai1[j1 + i1 * k] = biomegenbase.biomeID;
                }
                else
                {
                    ai1[j1 + i1 * k] = allowedBiomes[nextInt(allowedBiomes.length)].biomeID;
                }
            }
        }

        return ai1;
    }
}
