package net.minecraft.src;

public class GenLayerDimensionOcean2 extends GenLayer
{
    private WorldProviderBase worldProvider;

    public GenLayerDimensionOcean2(long l, GenLayer genlayer, WorldProviderBase worldproviderbase)
    {
        super(l);
        parent = genlayer;
        worldProvider = worldproviderbase;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int i, int j, int k, int l)
    {
        int ai[] = parent.getInts(i, j, k, l);
        int ai1[] = IntCache.getIntCache(k * l);

        for (int i1 = 0; i1 < l; i1++)
        {
            for (int j1 = 0; j1 < k; j1++)
            {
                initChunkSeed(j1 + i, i1 + j);
                BiomeGenBase biomegenbase = worldProvider.setOceanBiomes(null, this);

                if (biomegenbase != null && ai[j1 + i1 * k] <= 0)
                {
                    ai1[j1 + i1 * k] = biomegenbase.biomeID;
                }
                else
                {
                    ai1[j1 + i1 * k] = nextInt(2) + 2;
                }
            }
        }

        return ai1;
    }
}
