package net.minecraft.src;

public class GenLayerDimensionMinorBiome extends GenLayer
{
    private WorldProviderBase worldProvider;

    public GenLayerDimensionMinorBiome(long l, GenLayer genlayer, WorldProviderBase worldproviderbase)
    {
        super(l);
        parent = genlayer;
        worldProvider = worldproviderbase;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int i, int j, int k, int l)
    {
        int ai[] = parent.getInts(i - 1, j - 1, k + 2, l + 2);
        int ai1[] = IntCache.getIntCache(k * l);

        for (int i1 = 0; i1 < l; i1++)
        {
            for (int j1 = 0; j1 < k; j1++)
            {
                initChunkSeed(j1 + i, i1 + j);
                int k1 = ai[j1 + 1 + (i1 + 1) * (k + 2)];

                if (nextInt(3) == 0)
                {
                    int l1 = k1;
                    BiomeGenBase biomegenbase = worldProvider.setMinorBiomes(BiomeGenBase.biomeList[k1], this);

                    if (biomegenbase != null)
                    {
                        l1 = biomegenbase.biomeID;
                    }

                    if (l1 != k1)
                    {
                        int i2 = ai[j1 + 1 + ((i1 + 1) - 1) * (k + 2)];
                        int j2 = ai[j1 + 1 + 1 + (i1 + 1) * (k + 2)];
                        int k2 = ai[((j1 + 1) - 1) + (i1 + 1) * (k + 2)];
                        int l2 = ai[j1 + 1 + (i1 + 1 + 1) * (k + 2)];

                        if (i2 == k1 && j2 == k1 && k2 == k1 && l2 == k1)
                        {
                            ai1[j1 + i1 * k] = l1;
                        }
                        else
                        {
                            ai1[j1 + i1 * k] = k1;
                        }
                    }
                    else
                    {
                        ai1[j1 + i1 * k] = k1;
                    }
                }
                else
                {
                    ai1[j1 + i1 * k] = k1;
                }
            }
        }

        return ai1;
    }
}
